# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171101_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
